version: "2.4"

services:

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: accidents
      POSTGRES_PASSWORD: PASSWORD
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  editor-data-helpers:
    build:
      context: editor-data-helpers
    ports:
      - "9000:9000"
    environment:
      POSTGRES_URL: postgresql://postgres:PASSWORD@postgres/accidents
    depends_on:
      postgres:
        condition: service_healthy

  